### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by PraanavPatel** [Ti-tanium/Texas-DPS-Appointment-Assistant#1]
Traceback (most recent call last):
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'publicapi.txdpsscheduler.com' doesn't match either of '*.txSchedulingAppServiceEnvironment.p.azurewebsites.us', '*.scm.txSchedulingAppServiceEnvironment.p.azurewebsites.us', 'txSchedulingAppServiceEnvironment.scm.p.azurewebsites.us'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='publicapi.txdpsscheduler.com', port=443): Max retries exceeded with url: /api/Eligibility (Caused by SSLError(CertificateError("hostname 'publicapi.txdpsscheduler.com' doesn't match either of '*.txSchedulingAppServiceEnvironment.p.azurewebsites.us', '*.scm.txSchedulingAppServiceEnvironment.p.azurewebsites.us', 'txSchedulingAppServiceEnvironment.scm.p.azurewebsites.us'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/dps_check_availability.py", line 53, in <module>
    res = requests.post(url='https://publicapi.txdpsscheduler.com/api/Eligibility', data=str(payload), headers=headers)
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/pranavpatel/Downloads/Texas-DPS-Appointment-Assistant-main/.venv/lib/python3.9/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='publicapi.txdpsscheduler.com', port=443): Max retries exceeded with url: /api/Eligibility (Caused by SSLError(CertificateError("hostname 'publicapi.txdpsscheduler.com' doesn't match either of '*.txSchedulingAppServiceEnvironment.p.azurewebsites.us', '*.scm.txSchedulingAppServiceEnvironment.p.azurewebsites.us', 'txSchedulingAppServiceEnvironment.scm.p.azurewebsites.us'")))

Process finished with exit code 1

**Comment by Yuhang-7** [comment]
Also endures a error on a wsl. Does the DPS lately change their website?
